// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Saved profiles, in the user's order. */
	listProfiles: () => typedError<ProfileSummary[], AppError>(__TAURI_INVOKE("list_profiles")),
	/**
	 *  Check a draft against the server without saving it (US1). Cancellable via `cancel_request`
	 *  with the same `request_id`; times out after 15 s (FR-006).
	 */
	testConnection: (draft: ProfileDraft, requestId: string) => typedError<TestResult, AppError>(__TAURI_INVOKE("test_connection", { draft, requestId })),
	/**  Cancel an in-flight `test_connection` or `connect`. Unknown ids are ignored. */
	cancelRequest: (requestId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_request", { requestId })),
	/**
	 *  Re-check the draft and save it as a new profile (FR-008). Fails with `duplicateProfile` if
	 *  the server is already saved.
	 */
	createProfile: (draft: ProfileDraft) => typedError<ProfileSummary, AppError>(__TAURI_INVOKE("create_profile", { draft })),
	/**
	 *  Update a profile from a full draft (FR-013). The new settings are checked first; with
	 *  `force`, they are saved even if the check fails. If the profile is active, the session
	 *  reconnects with the new settings.
	 */
	updateProfile: (profileId: string, draft: ProfileDraft, force: boolean) => typedError<ProfileSummary, AppError>(__TAURI_INVOKE("update_profile", { profileId, draft, force })),
	/**  Delete a profile (FR-012; the UI confirms first). If it was active, the session goes Idle. */
	deleteProfile: (profileId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_profile", { profileId })),
	/**  Reorder profiles to match `profile_ids` (FR-011). */
	reorderProfiles: (profileIds: string[]) => typedError<null, AppError>(__TAURI_INVOKE("reorder_profiles", { profileIds })),
	/**
	 *  Make a profile active and connect to it. Resolves once the attempt settles (connected,
	 *  offline, auth failed, or failed); progress also arrives as `connection-state` events.
	 *  Cancellable via `cancel_request`, which returns the session to Idle.
	 */
	connect: (profileId: string, requestId: string) => typedError<ConnectionSnapshot, AppError>(__TAURI_INVOKE("connect", { profileId, requestId })),
	/**  End the session (Idle). */
	disconnect: () => __TAURI_INVOKE<void>("disconnect"),
	/**  Current connection state, for UI hydration on window load. */
	getConnectionSnapshot: () => __TAURI_INVOKE<ConnectionSnapshot>("get_connection_snapshot"),
	/**  Current player state, for UI hydration. */
	playerSnapshot: () => typedError<PlayerSnapshot, AppError>(__TAURI_INVOKE("player_snapshot")),
	/**  The 20 most recently added scenes on the active server (FR-001). */
	listRecentScenes: () => typedError<SceneListItem[], AppError>(__TAURI_INVOKE("list_recent_scenes")),
	/**
	 *  The spike's test set: a few random 4K, WMV, VP9, AV1, MPEG-4, and FLV scenes, in one
	 *  request (research R7). Each call reshuffles.
	 */
	listTestScenes: () => typedError<SceneGroup[], AppError>(__TAURI_INVOKE("list_test_scenes")),
	/**  Look up a scene and start playing its direct stream (FR-001, FR-003, FR-004). */
	playerOpen: (sceneId: string) => typedError<PlayerSnapshot, AppError>(__TAURI_INVOKE("player_open", { sceneId })),
	/**  Stop playback and release audio/video (FR-007). */
	playerClose: () => typedError<null, AppError>(__TAURI_INVOKE("player_close")),
	/**
	 *  Play/pause (FR-008). All control commands return immediately; results arrive as
	 *  `player-state` events (contract invariant 1).
	 */
	playerTogglePause: () => typedError<null, AppError>(__TAURI_INVOKE("player_toggle_pause")),
	playerSetPaused: (paused: boolean) => typedError<null, AppError>(__TAURI_INVOKE("player_set_paused", { paused })),
	/**  Absolute seek: keyframe-fast while dragging, `exact` on release. */
	playerSeek: (positionSeconds: number | null, exact: boolean) => typedError<null, AppError>(__TAURI_INVOKE("player_seek", { positionSeconds, exact })),
	/**  Relative seek (±10 s for skip buttons and arrow keys). */
	playerSeekRelative: (seconds: number | null) => typedError<null, AppError>(__TAURI_INVOKE("player_seek_relative", { seconds })),
	/**  Clamped to 0.25–4.0 by the player. */
	playerSetSpeed: (speed: number | null) => typedError<null, AppError>(__TAURI_INVOKE("player_set_speed", { speed })),
	/**  Clamped to 0–100 by the player. */
	playerSetVolume: (volume: number | null) => typedError<null, AppError>(__TAURI_INVOKE("player_set_volume", { volume })),
	playerSetMuted: (muted: boolean) => typedError<null, AppError>(__TAURI_INVOKE("player_set_muted", { muted })),
	/**  One frame forward or back; only while paused. */
	playerFrameStep: (direction: FrameDirection) => typedError<null, AppError>(__TAURI_INVOKE("player_frame_step", { direction })),
	/**  From the ended state: back to the start and play (FR-015). */
	playerReplay: () => typedError<null, AppError>(__TAURI_INVOKE("player_replay")),
	/**  Enter or leave fullscreen (the window), mirrored into the player snapshot. */
	playerSetFullscreen: (fullscreen: boolean) => typedError<null, AppError>(__TAURI_INVOKE("player_set_fullscreen", { fullscreen })),
	/**  Confine mpv's drawing to the scene view's area; `None` fills the window (fullscreen). */
	playerSetViewport: (viewport: {
	x: number,
	y: number,
	width: number,
	height: number,
} | null) => __TAURI_INVOKE<void>("player_set_viewport", { viewport }),
	/**
	 *  Debug builds only: a scene to open once connected (`SSV_DEBUG_OPEN`), for checking the video
	 *  surface without clicking through the UI.
	 */
	debugOpenScene: () => __TAURI_INVOKE<string | null>("debug_open_scene"),
	/**  Measurements for the decision record. Debug builds only. */
	playerStats: () => typedError<PlayerStats, AppError>(__TAURI_INVOKE("player_stats")),
};

/** Events */
export const events = {
	connectionState: makeEvent<ConnectionStateEvent>("connection-state"),
	playerState: makeEvent<PlayerStateEvent>("player-state"),
	profilesChanged: makeEvent<ProfilesChangedEvent>("profiles-changed"),
};

/* Types */
/**
 *  Every fallible command returns this. Connection problems are wrapped as `Connect` so the UI
 *  can show the matching plain-language message; the rest are app-level problems.
 */
export type AppError = { kind: "connect"; failure: ConnectFailure } | 
/**  The display name is empty after trimming, or longer than 64 characters. */
{ kind: "invalidDisplayName"; reason: string } | { kind: "profileNotFound"; id: string } | 
/**  Stash has no scene with this id. */
{ kind: "sceneNotFound"; id: string } | 
/**  The scene exists but has no file to play. */
{ kind: "noPlayableFile"; id: string } | 
/**
 *  `profiles.json` has a newer schema version than this build understands. It is left
 *  untouched rather than overwritten.
 */
{ kind: "unsupportedProfilesVersion"; found: number } | 
/**  Reading or writing the local config failed. */
{ kind: "storage"; message: string } | 
/**  A tab set failed validation (empty, missing selection, or over the size limits). */
{ kind: "tabSetInvalid"; reason: string } | 
/**  The system couldn't open a folder or file for the user (e.g. the log folder). */
{ kind: "openFailed"; detail: string } | 
/**  The request was cancelled by the user. */
{ kind: "cancelled" } | 
/**  Anything else that shouldn't happen (for example the HTTP client failing to build). */
{ kind: "internal"; message: string };

/**  A classified connection failure. No variant carries a raw response body. */
export type ConnectFailure = 
/**  The address can't be used (no host, bad scheme). Detected before any network call. */
{ kind: "invalidAddress"; reason: string } | 
/**  Nothing answered at any of the tried URLs. */
{ kind: "unreachable"; tried: string[] } | 
/**  No response within the overall connection budget (15 s). */
{ kind: "timeout" } | 
/**  Something answered, but it isn't Stash. */
{ kind: "notStash"; status: number | null } | 
/**  Stash requires an API key and none was sent. */
{ kind: "apiKeyRequired" } | 
/**  Stash rejected the API key that was sent. */
{ kind: "apiKeyRejected" } | 
/**  Stash has no authentication configured, but rejected the (wrong) key that was sent. */
{ kind: "apiKeyInvalidButNotRequired" } | 
/**  Stash is older than the minimum supported version. */
{ kind: "unsupportedVersion"; found: string; minimum: string } | 
/**  Stash reports it needs setup or a migration (`systemStatus.status` is not `OK`). */
{ kind: "serverNotReady"; status: string } | 
/**  Strict certificate checking is on and the server's certificate couldn't be verified. */
{ kind: "certificateNotVerified" } | 
/**  A profile for this server already exists. */
{ kind: "duplicateProfile"; existingId: string };

export type ConnectionSnapshot = {
	profileId: string | null,
	state: SessionState,
	/**  Known after the first successful handshake (FR-020). */
	security: SecurityState | null,
	/**  Base URL after redirects, once known. */
	finalUrl: string | null,
	/**  From the last successful probe. */
	server: ServerInfo | null,
	/**  ISO 8601; last successful health check or probe. */
	lastContactAt: string | null,
};

/**  Emitted on every connection state transition. */
export type ConnectionStateEvent = ConnectionSnapshot;

export type FrameDirection = "forward" | "back";

/**  Library summary shown after connecting (FR-007). */
export type LibraryCounts = {
	scenes: number,
	images: number,
	galleries: number,
	performers: number,
};

export type PlayerError = { kind: "notConnected" } | { kind: "sceneNotFound" } | { kind: "noPlayableFile" } | 
/**  The stream couldn't be opened (network error, 401/403, 404). */
{ kind: "streamUnreachable" } | 
/**  mpv couldn't decode the file. */
{ kind: "unsupportedFormat" } | { kind: "playbackFailed"; detail: string };

export type PlayerSnapshot = {
	sceneId: string | null,
	title: string | null,
	state: PlayerStateKind,
	positionSeconds: number | null,
	durationSeconds: number | null,
	paused: boolean,
	/**  0.25–4.0. */
	speed: number | null,
	/**  0–100. */
	volume: number | null,
	muted: boolean,
	fullscreen: boolean,
	/**  mpv `hwdec-current`, e.g. `vaapi`, or `no` for software decoding. */
	hwdec: string | null,
	/**  Embedded tracks (FR-014); read-only in the spike. */
	tracks: Track[],
	error: PlayerError | null,
};

/**  Emitted on every player state change; position updates are throttled to ~4/s. */
export type PlayerStateEvent = PlayerSnapshot;

/**  Player state (data-model.md "PlayerState and transitions"). */
export type PlayerStateKind = "idle" | "loading" | "playing" | "paused" | 
/**  End of file reached; the last frame stays up with a replay option (FR-015). */
"ended" | "error";

/**  Playback measurements for the spike's decision record (debug builds only). */
export type PlayerStats = {
	/**  From opening a scene to its first rendered frame. */
	openToFirstFrameMs: number | null,
	/**  From the last seek to the next rendered frame. */
	lastSeekToFrameMs: number | null,
	/**  mpv `frame-drop-count` + `decoder-frame-drop-count`; `i32` keeps it TypeScript-safe. */
	droppedFrames: number,
	hwdec: string | null,
};

/**  What the connection form submits for `test_connection`, `create_profile`, `update_profile`. */
export type ProfileDraft = {
	displayName?: string | null,
	/**  Raw user input; normalised by `connection::address`. */
	address: string,
	/**  Whitespace-trimmed; an empty string is treated as no key. */
	apiKey?: string | null,
	strictTls?: boolean,
};

/**  The profile as sent to the UI (contracts/tauri-commands.md `ProfileSummary`). */
export type ProfileSummary = {
	id: string,
	displayName: string,
	baseUrl: string,
	strictTls: boolean,
	apiKey: string | null,
	/**  ISO 8601. */
	lastUsedAt: string | null,
};

/**  Emitted after every profile create, update, delete, or reorder, with the full list. */
export type ProfilesChangedEvent = ProfileSummary[];

/**  A labelled group of scenes (the spike's test set: 4K, WMV, …). */
export type SceneGroup = {
	label: string,
	scenes: SceneListItem[],
};

/**  One row of the "recently added" picker. */
export type SceneListItem = {
	id: string,
	/**  The scene title, or the primary file's basename when the title is empty. */
	title: string,
	durationSeconds: number | null,
	/**  `width×height`, e.g. `1920×1080`. */
	resolution: string | null,
	videoCodec: string | null,
	container: string | null,
};

/**  How secure the current connection is, shown in the connection indicator at all times. */
export type SecurityState = 
/**  Plain http. */
"unencrypted" | 
/**  https with certificate checking off (the default): encrypted, but nothing was verified. */
"encryptedUnverified" | 
/**  https with strict checking on and a successful handshake. */
"encryptedVerified";

/**  Facts read from the server on connect (data-model.md "ServerInfo"). */
export type ServerInfo = {
	/**  For example `v0.31.1`, or `unknown` if the server didn't report one. */
	version: string,
	versionStatus: VersionStatus,
	appSchema: number,
	counts: LibraryCounts,
};

/**  Session state (data-model.md "ConnectionState and transitions"). */
export type SessionState = { kind: "idle" } | { kind: "connecting"; attemptUrl: string } | { kind: "connected" } | 
/**  Retrying with backoff. `next_retry_at` is ISO 8601 wall-clock time. */
{ kind: "offline"; attempt: number; nextRetryAt: string } | 
/**  The key was missing, rejected, or wrong. Retries stop until the key is updated (FR-017). */
{ kind: "authFailed"; failure: ConnectFailure } | { kind: "failed"; failure: ConnectFailure };

/**  What `test_connection` returns to the UI (contracts/tauri-commands.md `TestResult`). */
export type TestResult = {
	/**  Final base URL after redirects, as shown to the user. */
	normalizedUrl: string,
	security: SecurityState,
	server: ServerInfo,
};

export type Track = {
	/**  mpv's per-kind track id (`track-list/N/id`); small, so `i32` (TypeScript-safe). */
	id: number,
	kind: TrackKind,
	title: string | null,
	language: string | null,
	codec: string | null,
	default: boolean,
	external: boolean,
};

export type TrackKind = "video" | "audio" | "subtitle";

/**  How confident we are that the server is compatible. */
export type VersionStatus = 
/**  A release at or above the minimum. */
"supported" | 
/**
 *  A git-describe or pre-release build whose base version meets the minimum. Shown with a
 *  compatibility warning.
 */
"developmentBuild" | 
/**
 *  The version couldn't be parsed, but the database schema is new enough. Shown with a
 *  warning.
 */
"unknownButCompatible";

/**  Where the scene view's video area is, in window-relative CSS pixels (004 research R6). */
export type Viewport = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

