// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Saved profiles, in the user's order. */
	listProfiles: () => typedError<ProfileSummary[], AppError>(__TAURI_INVOKE("list_profiles")),
	/**
	 *  Check a draft against the server without saving it (US1). Cancellable via `cancel_request`
	 *  with the same `request_id`; times out after 15 s (FR-006).
	 */
	testConnection: (draft: ProfileDraft, requestId: string) => typedError<TestResult, AppError>(__TAURI_INVOKE("test_connection", { draft, requestId })),
	/**  Cancel an in-flight `test_connection` (or `connect`, later). Unknown ids are ignored. */
	cancelRequest: (requestId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_request", { requestId })),
	/**
	 *  Re-check the draft and save it as a new profile (FR-008). Fails with `duplicateProfile` if
	 *  the server is already saved.
	 */
	createProfile: (draft: ProfileDraft) => typedError<ProfileSummary, AppError>(__TAURI_INVOKE("create_profile", { draft })),
};

/* Types */
/**
 *  Every fallible command returns this. Connection problems are wrapped as `Connect` so the UI
 *  can show the matching plain-language message; the rest are app-level problems.
 */
export type AppError = { kind: "connect"; failure: ConnectFailure } | 
/**  The display name is empty after trimming, or longer than 64 characters. */
{ kind: "invalidDisplayName"; reason: string } | { kind: "profileNotFound"; id: string } | 
/**
 *  `profiles.json` has a newer schema version than this build understands. It is left
 *  untouched rather than overwritten.
 */
{ kind: "unsupportedProfilesVersion"; found: number } | 
/**  Reading or writing the local config failed. */
{ kind: "storage"; message: string } | 
/**  The request was cancelled by the user. */
{ kind: "cancelled" } | 
/**  Anything else that shouldn't happen (for example the HTTP client failing to build). */
{ kind: "internal"; message: string };

/**  A classified connection failure. No variant carries a raw response body. */
export type ConnectFailure = 
/**  The address can't be used (no host, bad scheme). Detected before any network call. */
{ kind: "invalidAddress"; reason: string } | 
/**  Nothing answered at any of the tried URLs. */
{ kind: "unreachable"; tried: string[] } | 
/**  No response within the overall connection budget (15 s). */
{ kind: "timeout" } | 
/**  Something answered, but it isn't Stash. */
{ kind: "notStash"; status: number | null } | 
/**  Stash requires an API key and none was sent. */
{ kind: "apiKeyRequired" } | 
/**  Stash rejected the API key that was sent. */
{ kind: "apiKeyRejected" } | 
/**  Stash has no authentication configured, but rejected the (wrong) key that was sent. */
{ kind: "apiKeyInvalidButNotRequired" } | 
/**  Stash is older than the minimum supported version. */
{ kind: "unsupportedVersion"; found: string; minimum: string } | 
/**  Stash reports it needs setup or a migration (`systemStatus.status` is not `OK`). */
{ kind: "serverNotReady"; status: string } | 
/**  Strict certificate checking is on and the server's certificate couldn't be verified. */
{ kind: "certificateNotVerified" } | 
/**  A profile for this server already exists. */
{ kind: "duplicateProfile"; existingId: string };

/**  Library summary shown after connecting (FR-007). */
export type LibraryCounts = {
	scenes: number,
	images: number,
	galleries: number,
	performers: number,
};

/**  What the connection form submits for `test_connection`, `create_profile`, `update_profile`. */
export type ProfileDraft = {
	displayName?: string | null,
	/**  Raw user input; normalised by `connection::address`. */
	address: string,
	/**  Whitespace-trimmed; an empty string is treated as no key. */
	apiKey?: string | null,
	strictTls?: boolean,
};

/**  The profile as sent to the UI (contracts/tauri-commands.md `ProfileSummary`). */
export type ProfileSummary = {
	id: string,
	displayName: string,
	baseUrl: string,
	strictTls: boolean,
	apiKey: string | null,
	/**  ISO 8601. */
	lastUsedAt: string | null,
};

/**  Facts read from the server on connect (data-model.md "ServerInfo"). */
export type ServerInfo = {
	/**  For example `v0.31.1`, or `unknown` if the server didn't report one. */
	version: string,
	versionStatus: VersionStatus,
	appSchema: number,
	counts: LibraryCounts,
};

/**  What `test_connection` returns to the UI (contracts/tauri-commands.md `TestResult`). */
export type TestResult = {
	/**  Final base URL after redirects, as shown to the user. */
	normalizedUrl: string,
	server: ServerInfo,
};

/**  How confident we are that the server is compatible. */
export type VersionStatus = 
/**  A release at or above the minimum. */
"supported" | 
/**
 *  A git-describe or pre-release build whose base version meets the minimum. Shown with a
 *  compatibility warning.
 */
"developmentBuild" | 
/**
 *  The version couldn't be parsed, but the database schema is new enough. Shown with a
 *  warning.
 */
"unknownButCompatible";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

